name: multidecade-data
channels:
  - bioconda
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.3.0
  - aioeasywebdav=2.4.0
  - aiohttp=3.7.4.post0
  - amply=0.1.4
  - anyio=3.3.3
  - appdirs=1.4.4
  - argon2-cffi=21.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - atk-1.0=2.36.0
  - atlite=0.2.5
  - attmap=0.13.0
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.0
  - bleach=4.1.0
  - bokeh=2.4.1
  - boost-cpp=1.74.0
  - boto3=1.18.60
  - botocore=1.21.60
  - bottleneck=1.3.2
  - branca=0.4.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.10.8
  - cachetools=4.2.4
  - cairo=1.16.0
  - cartopy=0.20.1
  - cdsapi=0.5.1
  - certifi=2021.10.8
  - cffi=1.14.6
  - cfitsio=3.470
  - cftime=1.5.1
  - chardet=4.0.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.0.0
  - coincbc=2.10.5
  - colorama=0.4.4
  - configargparse=1.5.3
  - connection_pool=0.0.3
  - convertdate=2.3.2
  - cryptography=3.4.8
  - curl=7.79.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2021.3.1
  - dask-core=2021.3.1
  - datrie=0.8.2
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - distributed=2021.3.1
  - docutils=0.17.1
  - dropbox=11.20.0
  - entrypoints=0.3
  - esgf-pyclient=0.3.0
  - expat=2.4.1
  - fftw=3.3.10
  - filechunkio=1.8
  - filelock=3.3.0
  - fiona=1.8.20
  - folium=0.12.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - freexl=1.0.6
  - fribidi=1.0.10
  - fsspec=2021.10.0
  - ftputil=5.0.1
  - gdal=3.3.2
  - gdk-pixbuf=2.42.6
  - geopandas=0.10.1
  - geopandas-base=0.10.1
  - geos=3.9.1
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - ghostscript=9.54.0
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.24
  - google-api-core=2.1.0
  - google-api-python-client=2.26.1
  - google-auth=2.3.0
  - google-auth-httplib2=0.1.0
  - google-cloud-core=2.1.0
  - google-cloud-storage=1.42.3
  - google-crc32c=1.1.2
  - google-resumable-media=2.0.3
  - googleapis-common-protos=1.53.0
  - graphite2=1.3.13
  - graphviz=2.49.1
  - grpcio=1.38.1
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=3.0.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - heapdict=1.0.1
  - hijri-converter=2.2.2
  - holidays=0.11.3.1
  - httplib2=0.20.1
  - icu=68.1
  - idna=2.10
  - imagemagick=7.1.0_10
  - importlib-metadata=4.8.1
  - iniconfig=1.1.1
  - ipykernel=6.4.1
  - ipython=7.28.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.2
  - jmespath=0.10.0
  - joblib=1.1.0
  - jpeg=9d
  - json-c=0.15
  - json5=0.9.5
  - jsonschema=4.1.0
  - jupyter-server-mathjax=0.2.3
  - jupyter_client=7.0.6
  - jupyter_core=4.8.1
  - jupyter_server=1.11.1
  - jupyterlab=3.1.18
  - jupyterlab-git=0.33.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.2
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - korean_lunar_calendar=0.2.1
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=7.79.1
  - libdap4=3.20.6
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgd=2.3.3
  - libgdal=3.3.2
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.68.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.18.1
  - librsvg=2.52.1
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.2.1
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - locket=0.2.0
  - logmuse=0.2.6
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - markupsafe=2.0.1
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - more-itertools=8.10.0
  - msgpack-python=1.0.2
  - multidict=5.2.0
  - munch=2.5.0
  - nbclassic=0.3.2
  - nbclient=0.5.4
  - nbconvert=6.2.0
  - nbdime=3.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - netcdf4=1.5.7
  - networkx=2.5
  - notebook=6.4.4
  - nspr=4.30
  - nss=3.69
  - numexpr=2.7.3
  - numpy=1.21.2
  - oauth2client=4.1.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.3
  - pandoc=2.14.2
  - pandocfilters=1.5.0
  - pango=1.48.10
  - paramiko=2.8.0
  - parso=0.8.2
  - partd=1.2.0
  - patsy=0.5.2
  - pcre=8.45
  - peppy=0.31.1
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=21.3
  - pixman=0.40.0
  - pkg-config=0.29.2
  - pluggy=1.0.0
  - ply=3.11
  - poppler=21.09.0
  - poppler-data=0.4.11
  - postgresql=13.3
  - prettytable=2.2.1
  - progressbar2=3.53.1
  - proj=8.1.1
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - protobuf=3.18.1
  - psutil=5.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.5.1
  - py=1.10.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.10.0
  - pygraphviz=1.7
  - pymeeus=0.5.11
  - pynacl=1.4.0
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pyproj=3.2.1
  - pyrsistent=0.17.3
  - pysftp=0.2.9
  - pyshp=2.1.3
  - pysocks=1.7.1
  - pytest=6.2.5
  - python=3.8.12
  - python-dateutil=2.8.2
  - python-graphviz=0.17
  - python-irodsclient=1.0.0
  - python-utils=2.5.6
  - python_abi=3.8
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyyaml=5.4.1
  - pyzmq=22.3.0
  - rasterio=1.2.10
  - ratelimiter=1.2.0
  - readline=8.1
  - requests=2.25.1
  - requests-unixsocket=0.2.0
  - requests_cache=0.4.13
  - rsa=4.7.2
  - rtree=0.9.7
  - s3transfer=0.5.0
  - scikit-learn=1.0
  - scipy=1.7.1
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.0
  - setuptools=58.2.0
  - shapely=1.7.1
  - simplejson=3.17.5
  - six=1.16.0
  - slacker=0.14.0
  - smart_open=5.2.1
  - smmap=3.0.5
  - snakemake=6.9.1
  - snakemake-minimal=6.9.1
  - sniffio=1.2.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sqlite=3.36.0
  - statsmodels=0.13.0
  - stone=3.2.1
  - stopit=1.1.2
  - tabulate=0.8.9
  - tblib=1.7.0
  - terminado=0.12.1
  - testpath=0.5.0
  - threadpoolctl=3.0.0
  - tiledb=2.3.4
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.1
  - toposort=1.7
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.0
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzcode=2021c
  - tzdata=2021c
  - ubiquerg=0.6.1
  - uritemplate=3.0.1
  - urllib3=1.26.7
  - veracitools=0.1.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - webob=1.8.7
  - websocket-client=0.57.0
  - wheel=0.37.0
  - wrapt=1.13.2
  - xarray=0.19.0
  - xerces-c=3.2.3
  - xmlrunner=1.7.7
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2021.9.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.5.1
  - zeromq=4.3.4
  - zict=2.0.0
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - lckr-jupyterlab-variableinspector==3.0.9
